### ISSUE TITLE
Possibly imported wrong package

### ISSUE THREAD

**Issue by unnamed420** [dcetin/Simple-CV#1]
Dear Mr. Cetin,

I've had issues regarding the `subfiles` package that is included on line 7 in the file `simplecv.sty`.
Specifically I got the error message
```
Undefined control sequence.
l.36 \import
    {sections/}{education.tex}
```
My current fix is to use the `import` instead of the `subfiles`-package, which works without any errors.

As I'm a beginner to the LaTeX world, I currently do not know whether any one else had similar problems, but if it reappears it might be an idea to change the import directive.

Doing `xelatex --version` yields
```XeTeX 3.14159265-2.6-0.99999 (TeX Live 2019/dev/Debian)
kpathsea version 6.3.1/dev
Copyright 2018 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 63.1; using 63.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.12; using 1.3.13
Compiled with HarfBuzz version 2.2.0; using 2.3.1
Compiled with libpng version 1.6.34; using 1.6.36
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.1; using 2.13.1
```

Best regards and stay healthy :)

edit: also using Biber v2.12 and debian 10 (buster) with kernel version 4.19.0-13. Tried it with lualatex as well but it didn't work either, otherwise above is still all accurate.

**Comment by dcetin** [comment]
Hello, sorry for very late reply, this was on my mind for quite a while but only started looking into this repo again now. I don't know how I didn't get any problems with my local setup or on overleaf but this makes sense. I included this change in [this PR](https://github.com/dcetin/Simple-CV/pull/3). Appreciate the comment, hoping to get back to this repo and test it a bit thoroughly this time!
